// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1089.X4RobotBuilder2016;

import org.usfirst.frc1089.X4RobotBuilder2016.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.*;
import org.usfirst.frc1089.X4RobotBuilder2016.subsystems.*;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public JoystickButton leftBtn1;
    public JoystickButton leftBtn3;
    public Joystick leftStick;
    public JoystickButton rightBtn1;
    public JoystickButton rightBtn2;
    public Joystick rightStick;
    public JoystickButton gamePadBtnA;
    public Joystick gamePad;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        gamePad = new Joystick(2);
        
        gamePadBtnA = new JoystickButton(gamePad, 1);
        gamePadBtnA.whileHeld(new Raise(0));
        rightStick = new Joystick(0);
        
        rightBtn2 = new JoystickButton(rightStick, 1);
        rightBtn2.whenPressed(new Raise(Shooter.LOW));
        rightBtn1 = new JoystickButton(rightStick, 1);
        rightBtn1.whenPressed(new Raise(Shooter.DOWN));
        leftStick = new Joystick(1);
        
        leftBtn3 = new JoystickButton(leftStick, 1);
        leftBtn3.whenPressed(new Raise(Shooter.HIGH));
        leftBtn1 = new JoystickButton(leftStick, 1);
        leftBtn1.whenPressed(new Raise(Shooter.MEDIUM));


        // SmartDashboard Buttons
        SmartDashboard.putData("Shoot", new Shoot());
        SmartDashboard.putData("StrongholdAuton", new StrongholdAuton());
        SmartDashboard.putData("Raise: DOWN", new Raise(Shooter.DOWN));
        SmartDashboard.putData("Raise: LOW", new Raise(Shooter.LOW));
        SmartDashboard.putData("Raise: MEDIUM", new Raise(Shooter.MEDIUM));
        SmartDashboard.putData("Raise: HIGH", new Raise(Shooter.HIGH));
        SmartDashboard.putData("MoveBall: IN", new MoveBall(Intake.ROLLER_IN));
        SmartDashboard.putData("MoveBall: OUT", new MoveBall(Intake.ROLLER_OUT));
        SmartDashboard.putData("MoveBall: OFF", new MoveBall(Intake.ROLLER_OFF));
        SmartDashboard.putData("DegreeRotate: Straight", new DegreeRotate(0));

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getLeftStick() {
        return leftStick;
    }

    public Joystick getRightStick() {
        return rightStick;
    }

    public Joystick getGamePad() {
        return gamePad;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

