// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1089.X4RobotBuilder2016.subsystems;

import org.usfirst.frc1089.X4RobotBuilder2016.RobotMap;
import org.usfirst.frc1089.X4RobotBuilder2016.commands.*;
import edu.wpi.first.wpilibj.DoubleSolenoid;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class IntakeDoor extends Subsystem {

    private final DoubleSolenoid elevator = RobotMap.intakeDoorElevator;

    // Put methods for controlling this subsystem here. Call these from Commands.
	/**
	 * <pre>
	 * public void lower(boolean readyToShoot)
	 * </pre>
	 * Raises or lowers the elevator
	 * @param lowered whether or not the door is closed
	 */
	public void lower(boolean lowered) {	//have to check values
		if (lowered)
			elevator.set(DoubleSolenoid.Value.kForward);
		else
			elevator.set(DoubleSolenoid.Value.kReverse);
	}

    public void initDefaultCommand() {

        setDefaultCommand(new LowerIntake(false));

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
}

