// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1089.X4RobotBuilder2016.subsystems;

import org.usfirst.frc1089.X4RobotBuilder2016.RobotMap;
import org.usfirst.frc1089.X4RobotBuilder2016.commands.*;
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.DoubleSolenoid;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Intake extends Subsystem {

    public static final double ROLLER_IN = -1.0;
    public static final double ROLLER_OUT = 1.0;
    public static final double ROLLER_OFF = 0.0;

    private final CANTalon roller = RobotMap.intakeRoller;

    // Put methods for controlling this subsystem here. Call these from Commands.
	/**
	 * <pre>
	 * public void moveBall(int speed)
	 * </pre>
	 * Sets the speed of the intake to move the ball.
	 * @param speed speed to set the intake wheels
	 */
	public void moveBall(double speed) {	
		roller.set(speed);	
	}
	
    public void initDefaultCommand() {
        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
}

